---
# tasks file for nrser.docker_build
# 
# build docker images using yarn for node packages

# Set up variables...

- when: docker_build_owner == None
  name: >-
    Set the `docker_build_name_tag` to `<name>:<tag>`
  set_fact:
    docker_build_name_tag: >-
      {{ docker_build_name }}:{{ docker_build_tag }}


- when: docker_build_owner != None
  name: >-
    Set the `docker_build_name_tag` to `<owner>/<name>:<tag>`
  set_fact:
    docker_build_name_tag: >-
      {{ docker_build_owner }}/{{ docker_build_name }}:{{ docker_build_tag }}


- when: docker_build_force
  name: >-
    Force build of image (overwrite if exists)
  tags:
  - build
  include_tasks: >-
    {{ role_path }}/tasks/build.yml


- when: not docker_build_force
  name: >-
    Build image if it doesn't already exist
  include_tasks: >-
    {{ role_path }}/tasks/conditional_build.yml
