---
# tasks file for nrser.docker_build
# 
# build docker images using yarn for node packages

- name: build build command
  tags:
  - always
  set_fact:
    docker_build_cmd: >-
      docker
      build .
      -t {{ docker_build_id }}
      {% if docker_build_file -%}
        --file {{ docker_build_file }}
      {%- endif %}
      {% for name, value in docker_build_args.iteritems() %}
        --build-arg {{ (name + '=' + value) |quote }}
      {% endfor %}
      {% if docker_build_yarn_cache %}
        --build-arg {{
          (
            'YARN_CACHE_FILE' +
            '=' +
            docker_build_yarn_cache_file
          ) | quote
        }}
      {% endif %}
      {% if docker_build_bundler_cache %}
        --build-arg {{
          (
            'BUNDLER_CACHE_FILE' +
            '=' +
            docker_build_bundler_cache_file
          ) | quote
        }}
      {% endif %}

- name: set build command
  tags:
  - always
  set_fact:
    docker_build_cmd: "{{ docker_build_cmd.replace('\n', '') }}"

- include: print.yml
  tags:
  - print

- include: build.yml
  tags:
  - build
